# Site settings
email: info@codefor.nl
description: >
  Open platform voor participatie projecten.
baseurl: ""
url: "http://www.consulproject.nl"
twitter_username: codefornl
github_username: codefornl

# Build settings
markdown: kramdown

# Documents files
files:
  - name: "administration_guide"
    format: "pdf"
  - name: "communication_guide"
    format: "pdf"
  - name: "polling_stations_manual"
    format: "pdf"
  - name: "participatory_budgeting"
    format: "pdf"
  - name: "slides_participatory_budgeting"
    format: "pdf"
  - name: "texts_information_sections"
    format: "pdf"
  - name: "annexes_voting"
    format: "pdf"
  - name: "recommended_actions_for_users"
    format: "pdf"
  - name: "resources_for_users"
    format: "pdf"
