# Site settings
email: info@codefor.nl
description: >
  Open Source Software voor participatie projecten.
baseurl: ""
url: "http://www.consulproject.nl"
twitter_username: codefornl
github_username: codefornl

# Build settings
markdown: kramdown
