kind: Service
apiVersion: v1
metadata:
  name: consul-site-pipeline
spec:
  selector:
    app: cosul-site
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-staging
  labels:
    app: consul-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-site
  template:
    metadata:
      labels:
        app: consul-site
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: consul-site
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
